### ISSUE TITLE
為什麼查回來的資料小於等於 1 時是查無資料呢？

### ISSUE THREAD

**Issue by azole** [huiyu580/nodejs-mfee16#2]
https://github.com/huiyu580/nodejs-mfee16/blob/1e81568fe4c9e636b5091f225da8371051a00276/crawler/app.js#L30

你試試看查 2618 看看。

**Comment by huiyu580** [comment]
謝謝老師，有修正了！

**Comment by azole** [comment]
很棒，測試過 OK 就可以關掉了～

提醒一下，這邊要注意的是，因為我們是去抓別人的 API，API 的格式可能會改變、改了他們可能也不會告訴我們，萬一他們把`(無符合之代碼或名稱)`這個訊息改掉，加減一個字之類的，你這邊就會無法辨識，但這個真的很難預防啦，就是提醒你可能會有這種情況。
